### ISSUE TITLE
Get X and Y position on moving etc

### ISSUE THREAD

**Issue by jongerenchaos** [AntoninoBonanno/DragDropAnnotate#1]
I want to get the position if i move or create a new item in the picture but it won't works.

If I use:
annotable.on('onAnnotationCreated', function (event, annotation) {
    alert(annotation);
});

I get [object Object] back on the alert window when i add a new Annotation to the picture. 
What do i wrong?

**Comment by jongerenchaos** [comment]
Solved: 

alert(JSON.stringify(annotation));

**Comment by AntoninoBonanno** [comment]
Yes the variable "annotation" is an object you can retrieve the X Y coordinates in this way:

``` 
anno.on('onMouseMoveOverItem', function (event, coordinate) {
 alert("[x: " + coordinate.x + " - y: " + coordinate.y + "]");
});

 anno.on('onAnnotationCreated', function (event, annotation) {
     console.log(annotation);
 
    alert(annotation.position.center.x + " " + annotation.position.center.y);
 });
```
