### ISSUE TITLE
Feature request: Name change

### ISSUE THREAD

**Issue by jongerenchaos** [AntoninoBonanno/DragDropAnnotate#2]
Is it possible to add the name change function from https://github.com/AntoninoBonanno/annotorious to this drapdropannotate script? It is very nice to change the name or other options (Like ID) when the image Annotations allready added to the image..

**Comment by AntoninoBonanno** [comment]
I think I didn't understand your request well.

You can overwrite an existing annotation by using the "addAnnotation (myAnnotation, annotationReplaced)" API
