### ISSUE TITLE
Marker/Pin Not showing on mobile while dragging

### ISSUE THREAD

**Issue by patriotaki** [AntoninoBonanno/DragDropAnnotate#4]
Hello,

Thank you so much for the mobile compatibility, let me know where I  can donate!

I noticed one issue tho, while dragging the marker on mobile devices it is invisible but it drops the marker in the correct spot

**Comment by AntoninoBonanno** [comment]
Hi @patriotaki,
I also noticed that the rotation, movement of the annotation did not happen well with the touch.

It should work fine now.
Can you please verify and then close the issue? Thank you

**Comment by patriotaki** [comment]
Hey @AntoninoBonanno its flawless now! Thank you, where can I donate?

**Comment by AntoninoBonanno** [comment]
@patriotaki No problem next time 😉
