### ISSUE TITLE
Feature request: Automatic Numbering

### ISSUE THREAD

**Issue by Camuflad** [AntoninoBonanno/DragDropAnnotate#6]
Hello Antonio,

I recently started using this plugin and I love it, but I'm having some problems with an extra that I needed.
I wanted to place an automatic numbering visible in the bottom right corner of each annotation I place on an image.
An example of what I want:
![Numbering](https://github.com/AntoninoBonanno/DragDropAnnotate/assets/159264237/c99585d5-73b4-4cbb-bfc4-ff72f73eb967)

I've tried to do it myself but without success, can you help me?

**Comment by AntoninoBonanno** [comment]
Hi @Camuflad,

I'm really happy that you are using my plugin.

Yes, I think it's doable, but unfortunately I can't do it quickly because I'm very busy.

I can schedule this feature implementation in March

**Comment by Camuflad** [comment]
Hello @AntoninoBonanno 

I'm not in a rush with this request, if you can get it in March that would be great.

Thank you very much.

**Comment by AntoninoBonanno** [comment]
Hi @Camuflad,

I added the "metadata" feature that allows you to display metadata text on the annotation.

In particular you can show:

- `id`: Print id of annotation if exists
- `text`: Print the annotation text
- `timestamp`: Print the annotation creation date
- `progressive`: Print the progressive counter insertion of annotations
- or you can pass a function to show custom text (show README.md for more details)

In your case you can use `progressive`.

you can also customize the font and position

```javascript
var annotable = $("#imageExample").annotable({
    draggable: ".annotation",
    metadata: {
      enabled: true,
      value: 'progressive',
      fontSize: "40px", //the font size of text
      fontFamily: "sans-serif", //the font family of text
      color: "#ff0000", //the color of text
      position: "bottom-right", //the position of text ["y-x"] -> y: ["top"|"middle"|"bottom"], x: ["left"|"center"|"right"]
      offsetX: -20,  //the offset from x
      offsetY: 10 //the offset from y
    }
});
```

I hope it covers your issue correctly
